<head>
	<?php
	load_js(array(
		"assets/admin/js/core/jquery.3.2.1.min.js",
		"assets/admin/js/core/popper.min.js",
		"assets/admin/js/core/bootstrap.min.js",
		"assets/admin/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js",
		"assets/admin/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js",
		"assets/admin/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js",
		"assets/admin/js/plugin/chart/chart.min.js",
		"assets/admin/js/plugin/jquery.sparkline/jquery.sparkline.min.js",
		"assets/admin/js/plugin/chart-circle/circles.min.js",
		"assets/admin/js/plugin/datatables/datatables.min.js",
		"assets/admin/js/plugin/bootstrap-notify/bootstrap-notify.min.js",
		"assets/admin/js/plugin/jqvmap/jquery.vmap.min.js",
		"assets/admin/js/plugin/jqvmap/maps/jquery.vmap.world.js",
		"assets/admin/js/plugin/sweetalert/sweetalert.min.js",
		"assets/admin/js/atlantis.min.js",
		"assets/admin/js/setting-demo.js",
		"assets/admin/js/demo.js",
		"assets/admin/js/hin_custom.js",
	))
	?>
</head>
